/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

;

/**
 *
 * @author Azael_Mendoza
 */
public class ViewOperaciones extends javax.swing.JPanel {

    /**
     * Creates new form ViewOperaciones
     */
    public ViewOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_numero_1 = new javax.swing.JLabel();
        jlb_numero_2 = new javax.swing.JLabel();
        jlb_resultado = new javax.swing.JLabel();
        jtf_numero_1 = new javax.swing.JTextField();
        jtf_numero_2 = new javax.swing.JTextField();
        jpnl_controles = new javax.swing.JPanel();
        jbtn_suma = new javax.swing.JButton();
        jbtn_resta = new javax.swing.JButton();
        jbtn_division = new javax.swing.JButton();
        jbtn_multiplicacion = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jlb_numero_1.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_numero_1.setForeground(new java.awt.Color(204, 204, 204));
        jlb_numero_1.setText("Numero 1:");

        jlb_numero_2.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_numero_2.setForeground(new java.awt.Color(204, 204, 204));
        jlb_numero_2.setText("Numero 2:");

        jlb_resultado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jlb_resultado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_resultado.setText("TutifrutiMVC");

        jtf_numero_1.setBackground(new java.awt.Color(102, 102, 102));
        jtf_numero_1.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_numero_1.setForeground(new java.awt.Color(204, 204, 204));

        jtf_numero_2.setBackground(new java.awt.Color(102, 102, 102));
        jtf_numero_2.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jtf_numero_2.setForeground(new java.awt.Color(204, 204, 204));

        jpnl_controles.setBackground(new java.awt.Color(51, 51, 51));
        jpnl_controles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_suma.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_suma.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jbtn_suma.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_suma.setText("+");
        jpnl_controles.add(jbtn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 60, 50));

        jbtn_resta.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_resta.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jbtn_resta.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_resta.setText("-");
        jpnl_controles.add(jbtn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 6, 60, 50));

        jbtn_division.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_division.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jbtn_division.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_division.setText("/");
        jpnl_controles.add(jbtn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 60, 50));

        jbtn_multiplicacion.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_multiplicacion.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jbtn_multiplicacion.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_multiplicacion.setText("x");
        jpnl_controles.add(jbtn_multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 60, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_numero_1)
                            .addComponent(jlb_numero_2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_numero_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_numero_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnl_controles, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jpnl_controles, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numero_1)
                            .addComponent(jtf_numero_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numero_2)
                            .addComponent(jtf_numero_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jlb_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_division;
    public javax.swing.JButton jbtn_multiplicacion;
    public javax.swing.JButton jbtn_resta;
    public javax.swing.JButton jbtn_suma;
    public javax.swing.JLabel jlb_numero_1;
    public javax.swing.JLabel jlb_numero_2;
    public javax.swing.JLabel jlb_resultado;
    public javax.swing.JPanel jpnl_controles;
    public javax.swing.JTextField jtf_numero_1;
    public javax.swing.JTextField jtf_numero_2;
    // End of variables declaration//GEN-END:variables
}
